const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Touch,
		C3.Plugins.AJAX,
		C3.Plugins.Sprite,
		C3.Behaviors.Anchor,
		C3.Plugins.TextBox,
		C3.Plugins.Text,
		C3.Behaviors.Fade,
		C3.Plugins.Browser,
		C3.Plugins.LocalStorage,
		C3.Plugins.TiledBg,
		C3.Plugins.Json,
		C3.Plugins.Arr,
		C3.Plugins.List,
		C3.Plugins.HTMLElement,
		C3.Behaviors.Tween,
		C3.Plugins.Model3D,
		C3.Plugins.Date,
		C3.Plugins.iframe,
		C3.Plugins.advert,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Browser.Acts.LoadStyleSheet,
		C3.Plugins.TextBox.Acts.SetCSSStyle,
		C3.Plugins.List.Acts.SetCSSStyle,
		C3.Plugins.System.Acts.SetVar,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.advert.Acts.CreateBanner,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.Json.Acts.Parse,
		C3.Plugins.Json.Cnds.ForEach,
		C3.Plugins.Json.Exps.Path,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.Json.Exps.CurrentKey,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Text.Cnds.HasTags,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Text.Acts.SetFontColor,
		C3.Plugins.Date.Exps.GetDay,
		C3.Plugins.Date.Exps.Now,
		C3.Plugins.Date.Exps.GetUTCMonth,
		C3.Plugins.Date.Exps.GetUTCYear,
		C3.Behaviors.Fade.Cnds.OnFadeInEnd,
		C3.Behaviors.Tween.Acts.SetAllTweensTime,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Sprite.Acts.SetEffectParam,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Behaviors.Fade.Cnds.OnWaitEnd,
		C3.Behaviors.Fade.Acts.SetFadeInTime,
		C3.Behaviors.Fade.Acts.SetWaitTime,
		C3.Behaviors.Fade.Acts.SetFadeOutTime,
		C3.Behaviors.Fade.Acts.RestartFade,
		C3.Behaviors.Fade.Cnds.OnFadeOutEnd,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.TextBox.Acts.SetText,
		C3.Plugins.System.Exps.regexreplace,
		C3.Plugins.TextBox.Exps.Text,
		C3.Plugins.TextBox.Cnds.CompareText,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.len,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Exps.right,
		C3.Plugins.System.Exps.left,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.random,
		C3.Plugins.AJAX.Acts.Request,
		C3.Plugins.AJAX.Acts.Post,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Exps.replace,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.advert.Acts.ShowBanner,
		C3.Plugins.List.Acts.Clear,
		C3.Plugins.Arr.Cnds.ArrForEach,
		C3.Plugins.Arr.Acts.Delete,
		C3.Plugins.List.Acts.AddItem,
		C3.Plugins.Arr.Exps.CurValue,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Json.Exps.CurrentValue,
		C3.Plugins.List.Acts.SetEnabled,
		C3.Plugins.TextBox.Acts.SetEnabled,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.List.Cnds.OnSelectionChanged,
		C3.Plugins.List.Exps.SelectedText,
		C3.Plugins.TextBox.Cnds.OnTextChanged,
		C3.Plugins.System.Exps.float,
		C3.Plugins.Text.Exps.Text,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.Browser.Acts.GoToURL
	];
};
self.C3_JsPropNameTable = [
	{Toque: 0},
	{AJAX: 0},
	{Âncora: 0},
	{fundo_inicial: 0},
	{botao_inicio: 0},
	{primeiro_nome_inicial: 0},
	{Esmaecer: 0},
	{Texto_boas_vindas: 0},
	{logo: 0},
	{texto_comum: 0},
	{logo2: 0},
	{Navegador: 0},
	{segundo_nome_inicial: 0},
	{estado: 0},
	{botao_enviar: 0},
	{ArmazenamentoLocal: 0},
	{PlanoDeFundoEmBlocos: 0},
	{clientes: 0},
	{cliente: 0},
	{Matriz_clientes: 0},
	{botao_agendar_venda: 0},
	{numero_telefone: 0},
	{dias_disponiveis: 0},
	{datas: 0},
	{matriz_datas: 0},
	{valor_venda: 0},
	{valores: 0},
	{Matriz_valores: 0},
	{valor_disponivel_para_compra_agendamento: 0},
	{botao_enviar_agendamento: 0},
	{PlanoDeFundoEmBlocos2: 0},
	{botao_ver_meus_agendamentos_agendamento: 0},
	{meus_agendamentos_ver_meus_agendamentos: 0},
	{botao_ver_meus_agendamentos_inicio: 0},
	{botao_agendar: 0},
	{botao_agendamentos: 0},
	{Texto: 0},
	{Texto2: 0},
	{PlanoDeFundoEmBlocos3: 0},
	{valor_receber_agendamento: 0},
	{PlanoDeFundoEmBlocos4: 0},
	{botao_ver_informacoes_da_loja: 0},
	{botao_abrir_no_google_maps: 0},
	{ElementoHTML: 0},
	{PlanoDeFundoEmBlocos5: 0},
	{Interpolação: 0},
	{logo3: 0},
	{texto_comum2: 0},
	{PlanoDeFundoEmBlocos6: 0},
	{Modelo3D: 0},
	{Modelo3D2: 0},
	{min_valor_agendamento: 0},
	{Data: 0},
	{texto_estado_loja: 0},
	{icone_estado_loja: 0},
	{Sprite2: 0},
	{iframe: 0},
	{Sprite: 0},
	{Sprite3: 0},
	{AnúncioMóvel: 0},
	{ElementoHTML2: 0},
	{Sprite4: 0},
	{versao: 0},
	{estadoloja: 0},
	{nome: 0},
	{sobrenome: 0},
	{numero_telefone2: 0},
	{ID_autenticacao: 0},
	{tela: 0},
	{requisicao: 0},
	{teste: 0},
	{carregando: 0},
	{acao: 0},
	{valor_disponivel: 0},
	{total_agendado: 0},
	{valor_inicial: 0},
	{agendou: 0},
	{data_agendamento: 0},
	{data_selecionada: 0},
	{valor_agendamento: 0},
	{dia: 0},
	{mes: 0},
	{ano: 0},
	{valor_alto: 0}
];

self.InstanceType = {
	Toque: class extends self.IInstance {},
	AJAX: class extends self.IInstance {},
	fundo_inicial: class extends self.ISpriteInstance {},
	botao_inicio: class extends self.ISpriteInstance {},
	primeiro_nome_inicial: class extends self.ITextInputInstance {},
	Texto_boas_vindas: class extends self.ITextInstance {},
	logo: class extends self.ISpriteInstance {},
	texto_comum: class extends self.ITextInstance {},
	logo2: class extends self.ISpriteInstance {},
	Navegador: class extends self.IInstance {},
	segundo_nome_inicial: class extends self.ITextInputInstance {},
	botao_enviar: class extends self.ISpriteInstance {},
	ArmazenamentoLocal: class extends self.IInstance {},
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	clientes: class extends self.IJSONInstance {},
	cliente: class extends self.IJSONInstance {},
	Matriz_clientes: class extends self.IArrayInstance {},
	botao_agendar_venda: class extends self.ISpriteInstance {},
	numero_telefone: class extends self.ITextInputInstance {},
	dias_disponiveis: class extends self.IListInstance {},
	datas: class extends self.IJSONInstance {},
	matriz_datas: class extends self.IArrayInstance {},
	valor_venda: class extends self.ITextInputInstance {},
	valores: class extends self.IJSONInstance {},
	Matriz_valores: class extends self.IArrayInstance {},
	valor_disponivel_para_compra_agendamento: class extends self.ITextInstance {},
	botao_enviar_agendamento: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos2: class extends self.ITiledBackgroundInstance {},
	botao_ver_meus_agendamentos_agendamento: class extends self.ISpriteInstance {},
	meus_agendamentos_ver_meus_agendamentos: class extends self.ITextInstance {},
	botao_ver_meus_agendamentos_inicio: class extends self.ISpriteInstance {},
	botao_agendar: class extends self.ISpriteInstance {},
	botao_agendamentos: class extends self.ISpriteInstance {},
	Texto: class extends self.ITextInstance {},
	Texto2: class extends self.ITextInstance {},
	PlanoDeFundoEmBlocos3: class extends self.ITiledBackgroundInstance {},
	valor_receber_agendamento: class extends self.ITextInstance {},
	PlanoDeFundoEmBlocos4: class extends self.ITiledBackgroundInstance {},
	botao_ver_informacoes_da_loja: class extends self.ISpriteInstance {},
	botao_abrir_no_google_maps: class extends self.ISpriteInstance {},
	ElementoHTML: class extends self.IHTMLElementInstance {},
	PlanoDeFundoEmBlocos5: class extends self.ITiledBackgroundInstance {},
	logo3: class extends self.ISpriteInstance {},
	texto_comum2: class extends self.ITextInstance {},
	PlanoDeFundoEmBlocos6: class extends self.ITiledBackgroundInstance {},
	Modelo3D: class extends self.I3DModelInstance {},
	Modelo3D2: class extends self.I3DModelInstance {},
	min_valor_agendamento: class extends self.ITextInstance {},
	Data: class extends self.IInstance {},
	texto_estado_loja: class extends self.ITextInstance {},
	icone_estado_loja: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	iframe: class extends self.IIframeInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	AnúncioMóvel: class extends self.IInstance {},
	ElementoHTML2: class extends self.IHTMLElementInstance {},
	Sprite4: class extends self.ISpriteInstance {}
}